services:
  - type: web
    name: newsapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn newsapp.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: newsapp.settings
 