# Generated by Django 5.2.4 on 2025-07-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_mfa_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
